### ISSUE TITLE
New Version @ HTML.5 ???

### ISSUE THREAD

**Issue by skynetradio** [versionstudio/vibestreamer#1]
Hello Erik

I wanted to ask you if you will continue to program the Vibestreamer at some point.
Because I've been looking for a program that's easy to use (administration) and runs on Windows machines for a long time.
An update to an HTML5 player would be really nice.

I am currently using your program for my web radio.
I just wanted to offer my archive so listeners can see what's available (archive).
Because nothing is currently playing because Flash is no longer available. 
For me it was important and that there is only access to the archive, so no play possible as a guest.

I would be very happy if you would find time to revive it.

Nice greetings from Vienna
Thomas

**Comment by versionstudio** [comment]
H there! Nice to see there's still people using this after so many years now. It's been over a decade now since I did anything with Vibe Streamer. I haven't had time to look into a way to patch this with HTML 5, and due to Vibe Streamer being a bit over complex design-wise it's not as quick as it should be. I'll see if I find time in the near future, since I've had other request this to be done. But otherwise I know there's a similar software called Subsonic that still has active development and probably does not rely on Flash as the player. 

Cheers
Erik

**Comment by skynetradio** [comment]
Hello Erik

Nice to hear that you might want to continue.
Now to your suggestions, I've gone through all of them. From Airsonic, Subsonic, Madsonic, etc., none of these programs came close to meeting my expectations.

I also used Ampache, but there are problems when importing the songs, only 1/3 is imported, no idea why.
I can't imagine that it's because of my VPN connection to the domain server. The network drives are all available and there are no other problems.

I would have liked Polaris, but for what can I create a user there and not assign rights??? Don't get the meaning behind it.

I would like to tell you what I imagine, maybe you will incorporate a few ideas into your new version ;-)

Vibestreamer has a really good advantage, which is that I can set exactly what a user is allowed to do.
To what extent this feature is still supported, I haven't quite figured out yet.

Now for improvements ;-)

1. Perfect user management as it currently is
2. The GUI doesn't have to win a beauty contest. (see https://github.com/agersant/polaris)
(it can also no longer be used on mobile phones, so set the window size)
Maybe the possibility to set dark or light mode, or also the main color of the selection elements.
3. Set the theme (window arrangement) for all accounts Fix
4. Set information about files, format, bitrate, etc.
5. Thicker font or readability of the text
6. Disable playlist creation

In my opinion, it is important that editing a file (ID tag) is not necessary, there are other tools for that.
Vibestreamer's strengths lie in fast indexing of the files, as is currently the case.
So the quick search for titles and artists.

For this, Foobar has also proven itself very well for me here you can enter word fragments from artists or titles and it always finds something.

I myself would like to use your software for my radio studio to give viewers the opportunity to look into our archive, to search and then to make a wish.

In any case, I still see a lot of potential in your software and it would be a real shame if it went under.

Would be happy if you continue to help you with ideas.

Greetings Tom

**Comment by versionstudio** [comment]
Hi! All good ideas, but there's no time or interest from my end to further develop the software. I simply haven't touched Vibe Streamer in 10+ years, and I released the source here as the final thing before leaving it as is. If anything, I might somewhere down the line look into replacing Flash so it at least works again, but for any further development it would need someone else to help me pick it up.

Really cool to see that you have such interest in it though, but for me there's simply not enough time to develop this much further than what it's at now.

**Comment by skynetradio** [comment]
Sorry for my late reply Eric.

So for me it's just the perfect software to show my archive to others but block them from playing. (the option of only browse) is there, and you can't play it anymore anyway.

In any case, it's really a shame that it doesn't continue.
I had 2 million songs indexed yesterday with no problems.
The database finds the titles or artists in ms.

Maybe the time will come when you want to continue. Unfortunately I can't help at all here because I don't have any programming knowledge. And only help you with tips.

Actually it does exactly what it should and what I need it for.
A simple quick tool to search my archive.

Just adjustments would be nice.
Dark mode, larger font in the files - more information about the files ready.

What kind of program was Vibestreamer programmed with Visual Studio? and C++.
I don't really have a clue about it, but I'd love to see it.

Greetings Tom

**Comment by Chevelle-Life** [comment]
Eric Nilsson,

It's pretty funny finding you discussing Vibe Streamer withing a few weeks of it crossing my mind again. I
have used and loved this app since the beginning, 2006 or so. I want to personally thank you for creating
and sharing this dope app and to let you know how much I and others loved it. I still have all my original
files and my fav skin. BBE-FSG.

I tried every media server app I could get my hands on back then, you know back when employers
blocked streaming services. I am one of those X - OiNK members (rip) with a 1.2TB Music library and still,
in 2023 I struggle to find a good, easy to use Music player, manager, streaming platform where it's easy
to find the songs I want to queue, one that I like and just works. That is why every few years Id search
for your site and see if you released any updates. Lol.

I'm not a programmer but hell, maybe It's time to learn, I know I'd kill for a good music streaming
system other than Plex that I can self-host again. Bonus if it had some library management features.
Anyway, you made something special to a few of us. So thanks.

After reading the posts I had to load up VS and good ole Microsoft still has IE 11 in windows 10 so the
skin almost fully loads. Attaching screenshots for fun.

Anyway, I get why you don’t want to revive it, I don’t blame ya. It was great though.

Dustin W.

![Vibe Streamer Skin 1](https://github.com/versionstudio/vibestreamer/assets/133985047/eb4af0db-6abf-44d4-85de-0acd8f78bfd8)
![Music Library Properties](https://github.com/versionstudio/vibestreamer/assets/133985047/a2897179-37b5-454e-bcbe-f344009eaae2)
![oink](https://github.com/versionstudio/vibestreamer/assets/133985047/9ed66f8a-5fa7-4f4a-9d6b-c0c3a825dff7)

**Comment by skynetradio** [comment]
Hello Chevelle Life

Nice to see and hear that I'm not alone here :-)
I felt the same way from Ampache to Polaris everything I tried
to organize my song database quickly and efficiently, and to give others insight.

Ampache just stopped importing after 758 songs, no one knows why, debug mode no errors.....

What I particularly like is and remains simple:
1.) It's the only server that works.
2.) Rights management at its finest, the only browse feature is worth its weight in gold (exactly what I was looking for)

We should teach ourselves programming or Chevelle-Life *laugh*

What I wanted to ask you Chevelle-Life where did you get this beautiful design from? Did you create it yourself?

Greetings Tom
